services:
  jekyll:
    build:
      context: .
    working_dir: /site
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload --force_polling
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/site
      - bundle:/usr/local/bundle

volumes:
  bundle:
